src/main/java/kr/go/sciencecenter/model/BoardType.java
package kr.go.sciencecenter.model;

import java.util.HashMap;
import java.util.LinkedHashMap;

public class BoardType {
	
	
	public static final HashMap<String, BoardType> BOARD_TYPES = new LinkedHashMap<String, BoardType>();

	static {
		// 1. 관람안내 게시판 없음
		// 2. 전시관람 전시물 리뷰 게시판 사라짐
		//BOARD_TYPES.put("exhibitionReview", new BoardType("exhibitionReview", false, "display", "전시물리뷰", "", true, false, true));
		// 3. 과학교육
		BOARD_TYPES.put("educationNotice", new BoardType("educationNotice", false, "education", "교육공지", "", false, false, false));
		BOARD_TYPES.put("classBoard", new BoardType("classBoard", false, "education", "수업게시판", "", false, false, false));
		BOARD_TYPES.put("fusionScience", new BoardType("fusionScience", false, "education", "과학융합탐구", "", false, false, false));
		BOARD_TYPES.put("reverseScience", new BoardType("reverseScience", false, "education", "거꾸로 과학탐구 교실", "", false, false, false));
		BOARD_TYPES.put("tree", new BoardType("tree", false, "education", "생각트리 과학탐구 교실", "", false, false, false));
		BOARD_TYPES.put("educationArchieve", new BoardType("educationArchieve", false, "education", "과학교육 자료실", "", false, false, false));
		// 4. 문화행사
		// 메인 행사 에 붙는 Board Type
		BOARD_TYPES.put("mainEventSeriesBasicInfo", new BoardType("mainEventSeriesBasicInfo", false, "mainEvent", "", "", false, false, false));
		BOARD_TYPES.put("mainEventSeriesNotice", new BoardType("mainEventSeriesNotice", false, "mainEvent", "", "", false, false, false));
		BOARD_TYPES.put("mainEventSeriesQna", new BoardType("mainEventSeriesQna", false, "mainEvent", "", "", false, false, false, true));
		BOARD_TYPES.put("mainEventSeriesFaq", new BoardType("mainEventSeriesFaq", false, "mainEvent", "", "", false, false, false));
		BOARD_TYPES.put("mainEventSeriesLibrary", new BoardType("mainEventSeriesLibrary", false, "mainEvent", "", "", false, false, false));
		BOARD_TYPES.put("mainEventSeriesPictures", new BoardType("mainEventSeriesPictures", false, "mainEvent", "", "", true, false, false));
		BOARD_TYPES.put("mainEventSeriesWinning", new BoardType("mainEventSeriesWinning", false, "mainEvent", "", "", true, false, false));
		BOARD_TYPES.put("mainEventSeriesRecommend", new BoardType("mainEventSeriesRecommend", false, "mainEvent", "", "", true, false, false));
		// 문화행사의 특별기획전 (마지막에 추가됨 )
		BOARD_TYPES.put("specialEvent", new BoardType("specialEvent", false, "events", "특별기획전", "", false, false, false));
		
		// 5. 예약신청 게시판 없음
		// 6.고객소통
		BOARD_TYPES.put("lostProperty", new BoardType("lostProperty", false, "communication", "분실물 목록", "", false, false, false));
		BOARD_TYPES.put("faqTotal", new BoardType("faqTotal", false, "communication", "전체 FAQ", "", false, false, false));
		BOARD_TYPES.put("faqScience", new BoardType("faqScience", false, "communication", "과학행사", "", false, false, false));
		BOARD_TYPES.put("faqEducation", new BoardType("faqEducation", false, "communication", "교육", "", false, false, false));
		BOARD_TYPES.put("faqRole", new BoardType("faqRole", false, "communication", "비영리법인", "", false, false, false));
		BOARD_TYPES.put("faqFacilities", new BoardType("faqFacilities", false, "communication", "시설", "", false, false, false));
		BOARD_TYPES.put("faqRestaurant", new BoardType("faqRestaurant", false, "communication", "식당", "", false, false, false));
		BOARD_TYPES.put("faqUser", new BoardType("faqUser", false, "communication", "연간회원", "", false, false, false));
		BOARD_TYPES.put("faqDisplay", new BoardType("faqDisplay", false, "communication", "전시 관람", "", false, false, false));
		BOARD_TYPES.put("faqReservation", new BoardType("faqReservation", false, "communication", "전시관예약", "", false, false, false));
		BOARD_TYPES.put("faqPark", new BoardType("faqPark", false, "communication", "주차", "", false, false, false));
		BOARD_TYPES.put("faqHomepage", new BoardType("faqHomepage", false, "communication", "홈페이지", "", false, false, false));
		BOARD_TYPES.put("faqMarketing", new BoardType("faqMarketing", false, "communication", "홍보자료", "", false, false, false));				
		BOARD_TYPES.put("normalLibrary", new BoardType("normalLibrary", false, "communication", "일반자료실", "", false, false, false));
		BOARD_TYPES.put("roleLibrary", new BoardType("roleLibrary", false, "communication", "관련규정자료실", "", false, false, false));
		BOARD_TYPES.put("scienceColumn", new BoardType("scienceColumn", false, "communication", "과학컬럼", "", false, true, false));
		BOARD_TYPES.put("opinions", new BoardType("opinions", false, "communication", "의견수렴", "", false, false, false, true));
		// 7. 과학관소개
		BOARD_TYPES.put("notice", new BoardType("notice", false, "introduce", "공지/공고", "", false, false, false));
		BOARD_TYPES.put("news", new BoardType("news", true, "introduce", "소식지", "", true, false, false));
		BOARD_TYPES.put("report", new BoardType("report", false, "introduce", "보도자료", "", false, false, false));
		BOARD_TYPES.put("sketch", new BoardType("sketch", true, "introduce", "현장스케치상", "/introduce/sketch?", true, false, false));
		BOARD_TYPES.put("programIntro", new BoardType("programIntro", true, "introduce", "과학관UCC", "", true, false, false));
		
		//BOARD_TYPES.put("chiefHistory", new BoardType("chiefHistory", false, "introduce", "기관장 동정", "", false, false, false));
		// 8. 정보공개
		BOARD_TYPES.put("sharedInfoArchive", new BoardType("sharedInfoArchive", false, "government", "공개정보자료실", "", false, false, false));

		//사이버과학관
//		BOARD_TYPES.put("digitalEducation", new BoardType("digitalEducation", true, "cyber", "디지털 교육관", "", true, true, false));
//		BOARD_TYPES.put("sciencePlay", new BoardType("sciencePlay", true, "cyber", "과학놀이터", "", true, true, false));
	};

	String name;
	boolean isGallary;
	String category;
	String nameAdmin;
	String path;
	boolean hasMainPicture;
	boolean isUrlType;
	boolean hasSubTitle;
	boolean replied;

	public BoardType(String name, boolean isGallary, String category, String nameAdmin, String path, boolean hasMainPicture,
			boolean isUrlType, boolean hasSubTitle) {

		setName(name);
		setGallary(isGallary);
		setCategory(category);
		setNameAdmin(nameAdmin);
		setPath(path);
		setHasMainPicture(hasMainPicture);
		setUrlType(isUrlType);
		setHasSubTitle(hasSubTitle);
		setReplied(false);
	}
	
	public BoardType(String name
			, boolean isGallary
			, String category
			, String nameAdmin
			, String path
			, boolean hasMainPicture
			, boolean isUrlType
			, boolean hasSubTitle
			, boolean replied) {
		
		setName(name);
		setGallary(isGallary);
		setCategory(category);
		setNameAdmin(nameAdmin);
		setPath(path);
		setHasMainPicture(hasMainPicture);
		setUrlType(isUrlType);
		setHasSubTitle(hasSubTitle);
		setReplied(replied);
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean isGallary() {
		return isGallary;
	}

	public void setGallary(boolean isGallary) {
		this.isGallary = isGallary;
	}

	public String getNameAdmin() {
		return nameAdmin;
	}

	public void setNameAdmin(String nameAdmin) {
		this.nameAdmin = nameAdmin;
	}

	public String getPath() {
		return path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public boolean isHasMainPicture() {
		return hasMainPicture;
	}

	public void setHasMainPicture(boolean hasMainPicture) {
		this.hasMainPicture = hasMainPicture;
	}

	public boolean isUrlType() {
		return isUrlType;
	}

	public void setUrlType(boolean isUrlType) {
		this.isUrlType = isUrlType;
	}

	public String getCategory() {
		return category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public boolean isHasSubTitle() {
		return hasSubTitle;
	}

	public void setHasSubTitle(boolean hasSubTitle) {
		this.hasSubTitle = hasSubTitle;
	}

	public boolean isReplied() {
		return replied;
	}

	public void setReplied(boolean replied) {
		this.replied = replied;
	}
}

src/main/java/kr/go/sciencecenter/model/Page.java
package kr.go.sciencecenter.model;

public class Page {
	private static final int DEFAULT_PAGE_COUNT = 10;
	private static final int SIDE_PAGE_COUNT = 3;
	
	int currentPage;
	int perPage;
	int totalItems;
	String className;
	String path;
	
	public int getCurrentPage() {
		return currentPage;
	}
	public void setCurrentPage(int currentPage) {
		this.currentPage = currentPage;
	}
	public int getTotalItems() {
		return totalItems;
	}
	public void setTotalItems(int totalItems) {
		this.totalItems = totalItems;
	}
	public int getPerPage() {
		return perPage;
	}
	public void setPerPage(int perPage) {
		this.perPage = perPage;
	}
	public String getPath() {
		return path;
	}
	public void setPath(String path) {
		this.path = path;
	}
	public String getClassName(){
		return this.className;
	}
	public void setClassName(String className){
		this.className = className;
	}
	public int getOffset(){
		if(this.currentPage > 1){
			return (currentPage - 1) * this.perPage;
		}else{
			return 0;
		}
	}
	
	public int getLimit(){
		return this.getOffset() + this.perPage;
	}
	
	public int getTotalPages(){
		if(this.totalItems % this.perPage == 0){
			return this.totalItems / this.perPage; 
		}else{
			return (this.totalItems / this.perPage) + 1;
		}
	}
	public int getBeginPage(){
		if(this.getTotalPages() <= DEFAULT_PAGE_COUNT || this.currentPage <= SIDE_PAGE_COUNT){
			return 1;
		}else{
			return this.currentPage - SIDE_PAGE_COUNT;
		}
	}
	public int getEndPage(){
		if(this.getTotalPages() <= DEFAULT_PAGE_COUNT){
			return this.getTotalPages();
		}else if(this.getTotalPages() - this.currentPage <= SIDE_PAGE_COUNT){
			return this.getTotalPages();
		}else{
			return this.currentPage + SIDE_PAGE_COUNT;
		}
	}
	
	public Page(){
		
	}
	
	public Page(int currentPage, int perPage){
		this.currentPage = currentPage;
		this.perPage = perPage;
	}
	
	public Page(int currentPage, int perPage, int totalItems){
		this.currentPage = currentPage;
		this.perPage = perPage;
		this.totalItems = totalItems;
	}
}

src/main/java/kr/go/sciencecenter/controller/BoardController.java
package kr.go.sciencecenter.controller;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.OutputStream;
import java.net.URLEncoder;
import java.util.Locale;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.env.Environment;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.SessionAttributes;

import kr.go.sciencecenter.model.Board;
import kr.go.sciencecenter.model.api.Member;
import kr.go.sciencecenter.service.BoardService;

@Controller
@RequestMapping("/boards")
@SessionAttributes(Member.CURRENT_MEMBER_NO)
public class BoardController {
	private static final Logger logger = LoggerFactory.getLogger(BoardController.class);

	@Autowired
	BoardService boardService;
	
	@Autowired
	private Environment env;

	@RequestMapping(value = "{type}", method = RequestMethod.GET)
	public String list(Model model, @PathVariable String type) {
		model.addAttribute("type", type);
		return "boards/index.app";
	}

//	@RequestMapping(value = "/getBoards/{type}", method = RequestMethod.POST)
//	public Model getBoards(@RequestBody String jsonStr, HttpServletRequest request, Model model, Locale locale,
//			@PathVariable String type, @RequestParam(value = "page", defaultValue = "1") Integer currentPage,
//			@RequestParam(value = "searchType", required = false) String searchType,
//			@RequestParam(value = "searchKey", required = false) String searchKey) {
//
//		String path = "/boards?";
//		Page page = null;
//		
//		List<Board> boards = null;
//		// faq total
//		if(type.equals("faqTotal")) {
//			List<String> faqTypes = new ArrayList<String>();
//			faqTypes.add("faqScience");
//			faqTypes.add("faqEducation");
//			faqTypes.add("faqRole");
//			faqTypes.add("faqFacilities");
//			faqTypes.add("faqRestaurant");
//			faqTypes.add("faqUser");
//			faqTypes.add("faqDisplay");
//			faqTypes.add("faqReservation");
//			faqTypes.add("faqPark");
//			faqTypes.add("faqHomepage");
//			faqTypes.add("faqMarketing");
//			
//			page = new Page(currentPage, 9, boardService.countFaqTotal(faqTypes));
//			
//			boards = boardService.listFaqTotal(faqTypes, page, searchType, searchKey, null);
//
//			model.addAttribute("boardType", "faqTotal");
//
//			page.setPath(path);
//			page.setClassName("mobile_page");
//			model.addAttribute("page", page);
//		}
//		else {
//			page = new Page(currentPage, 9, boardService.count(type, searchType, searchKey));
//			
//			boards = boardService.list(type, page, searchType, searchKey, null);
//			
//			model.addAttribute("boardType", BoardType.BOARD_TYPES.get(type));			
//		}
//		page.setPath(path);
//		page.setClassName("mobile_page");
//		model.addAttribute("page", page);
//		
//		model.addAttribute("boards", boards);
//		model.addAttribute("type", type);
//		return model;
//	}

	@RequestMapping(value = "/showBoard/{id}", method = RequestMethod.POST)
	public Model showBoard(@PathVariable int id, HttpServletRequest request, Model model, Locale locale) {

		Board board = boardService.find(id);
		if( board != null ) {
			boardService.addCount(board);
			board.setCount(board.getCount() + 1);
		}
		model.addAttribute("board", board);
		
		if (board.getBoardId() > 0) {
			Board parentBoard = boardService.find(board.getBoardId());
			model.addAttribute("prevBoard", boardService.getPrevBoard(parentBoard.getId(), parentBoard.getBoardType()));
			model.addAttribute("nextBoard", boardService.getNextBoard(parentBoard.getId(), parentBoard.getBoardType()));
		} else {
			model.addAttribute("prevBoard", boardService.getPrevBoard(id, board.getBoardType()));
			model.addAttribute("nextBoard", boardService.getNextBoard(id, board.getBoardType()));
		}

		return model;
	}

	@RequestMapping(value = "/board_attatchment/{id}/{filename:.+}", method = RequestMethod.GET)
	public void attatchmentDowonload(@PathVariable int id, @PathVariable String filename, HttpServletRequest request,
			HttpServletResponse response) {

		FileInputStream inputStream;
		OutputStream outStream;

		try {
			String fileName = filename;
			String mimeType = "application/octet-stream";

			String filePath = env.getProperty("file.path");
			filePath += "resources/upload/board_attatchment/" +id + "/"+filename;

			fileName = URLEncoder.encode(fileName, "utf-8");

			File downloadFile = new File(filePath);

			inputStream = new FileInputStream(downloadFile);

			response.setHeader("Content-Disposition", "attachment; filename=\"" + fileName + "\";");
			response.setHeader("Content-Transfer-Encoding", "binary");
			response.setContentType(mimeType);
			response.setContentLength((int) downloadFile.length());

			outStream = response.getOutputStream();

			byte[] buffer = new byte[4096];
			int bytesRead = -1;

			// write bytes read from the input stream into the output stream
			while ((bytesRead = inputStream.read(buffer)) != -1) {
				outStream.write(buffer, 0, bytesRead);
			}

			inputStream.close();
			outStream.close();
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}

src/main/webapp/WEB-INF/views/boards/form.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@ taglib uri="http://www.springframework.org/tags" prefix="spring"%>
<%@ taglib uri="http://www.springframework.org/security/tags"
	prefix="sec"%>

<form:form
	action="${param.action}?${_csrf.parameterName}=${_csrf.token}"
	method="${param.method }" commandName="board" modelAttribute="board"
	enctype="multipart/form-data">
	
	<form:input type="hidden" path="id" />
	<input type="hidden" name="boardType" value="${board.boardType}">

	
	<div class="form-group">
		<form:label path="title">제목</form:label>
		<form:input type='text' name='title' path='title'
			autofocus="autofocus" class="form-control"/>
	</div>
	<div class="form-group">
		<form:label path="content" class="active">내용</form:label>
		<form:textarea cols="80" path="content" name="content" rows="10" class="form-control ckeditor"></form:textarea>
	</div>
	
	<div class="form-group">
		<div class="text-right">
			<button class="btn btn-primary" type="submit"
				name="action">저장</button>
		</div>
	</div>
</form:form>

src/main/webapp/WEB-INF/views/boards/gallery.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8" session="true"%>
<%@ taglib uri="http://tiles.apache.org/tags-tiles" prefix="t"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib uri="http://www.springframework.org/tags" prefix="spring" %>

<div class="row gallery-boards">
	<c:forEach var="board" items="${boards }">
		<div class="col-sm-6 col-md-4">
			<div class="board-gallery-item">
				<c:choose>
					<c:when test="${boardType.urlType }">
						<a target="_blank" href="${board.linkUrl }">
							<div class="board-img">
								<img src="<c:url value='${baseFileUrl}' />${board.picture }" class="img-responsive" alt="${board.title }"/>
                            </div>
                            <div class="board-title">
                            	${board.title }
                            	<div class="gallery-board-date">
                            		<fmt:formatDate pattern="yyyy-MM-dd" value="${board.regDttm }" />
                            	</div>
                            </div>
						</a>
					</c:when>
					<c:otherwise>
						<a href="${param.path }/${board.id }">
							<div class="board-img">
								<img src="<c:url value='${baseFileUrl}' />${board.picture }" class="img-responsive" alt="${board.title }"/>
                            </div>
                            <div class="board-title">
                            	${board.title }
                            	<c:if test="${currentCategory eq 'main.nav.category6' }">
	                            	<div class="gallery-board-date">
	                            		<fmt:formatDate pattern="yyyy-MM-dd" value="${board.regDttm }" />
	                            	</div>
                            	</c:if>
                            	<c:if test="${boardType.hasSubTitle }">
                            		<div class="gallary-sub-title">
                            			${board.subTitle }
                            		</div>
                            	</c:if>
                            </div>
						</a>
					</c:otherwise>
				</c:choose>
			</div>
		</div>
	</c:forEach>
</div>

<div class="pagination-wrapper">
	<ul class="pagination">
		<c:if test="${page.beginPage > 1 }">
			<li>
				<a href="${param.path }?page=1" data-page="1" class="page-link {{page.className}}">
					<i class="fa fa-chevron-left"></i>
				</a>
			</li>
			<li>
				<a href="${param.path }?page=${page.beginPage - 1}" data-page="${page.beginPage - 1}" class="page-link"><i class="fa fa-ellipsis-h"></i></a>
			</li>
		</c:if>
		
		<c:forEach var="i" begin="${page.beginPage }" end="${page.endPage }" varStatus="loop">
			<c:choose>
				<c:when test="${i == page.currentPage }">
					<li class="active">
						<a href="#" class="page-link">${i }</a>
					</li>
				</c:when>
				<c:otherwise>
					<li>
						<a href="${param.path }?page=${i }" class="page-link">${i }</a>
					</li>
				</c:otherwise>
			</c:choose>
		</c:forEach>
		
		<c:if test="${page.endPage < page.totalPages }">
			<li>
				<a href="${param.path }?page=${page.endPage + 1}" data-page="${page.endPage + 1}" class="page-link"><i class="fa fa-ellipsis-h"></i></a>
			</li>
			<li>
				<a href="${param.path }?page=${page.endPage }" data-page="${page.endPage }" class="page-link"><spring:message code="page.last" text=""/>
					<i class="fa fa-chevron-right"></i>
				</a>
			</li>
		</c:if>
	</ul>
</div>

src/main/webapp/WEB-INF/views/boards/index.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form" %>


<script src="<c:url value='/resources/js/board.js'/> "></script>
<script id="board-list-template" type="text/x-handlebars-template">
	<div class="list-board-wrapper table-responsive">
			<table class="table">
				{{#compare boardType.name "scienceColumn" operator="=="}}
					<thead>
						<tr>
							<th>
								번호
							</th>
							<th>
								제목
							</th>
							<th>
								전시관
							</th>
							<th>
								전시물
							</th>
							<th>
								발행일
							</th>
							<th>
								작성자
							</th>
						</tr>
					</thead>
				{{else}}
					<thead>
						<tr>
							<th>
								번호
							</th>
							<th style="width:50%">
								제목
							</th>
							<th>
								작성자
							</th>
							<th>
								등록일
							</th>
							<th>
								조회수
							</th>
							<th>
								첨부파일
							</th>
						</tr>
					</thead>
				{{/compare}}
				{{#compare boardType.name "scienceColumn" operator="=="}}
					<tbody>
						{{#each boards}}
							<tr>
								<td>
									{{id}}
								</td>
								<td>
                                    <a href="{{link_url}}" target="_blank">{{title}}</a>
								</td>
								<td>
									{{building}}
								</td>
								<td>
									{{object}}
								</td>
								<td>
									
								</td>
								<td>
									
								</td>
							</tr>
						{{/each}}
					</tbody>
				{{else}}
					<tbody>
						{{#each boards}}
							<tr>
								<td>
									{{id}}
								</td>
								<td class="title">
									{{#if ../boardType.urlType }}
                                       <a target="_blank" href="{{linkUrl}}">{{title}}</a>
                                    {{else if ../../isFaqTotal}}
											<a href="{{../../../url}}/{{../../boardType}}/{{id}}">{{title}}</a>
									{{else}}
										<a href="{{../../../url}}/{{id}}">{{title}}</a>
										
                                    {{/if}}
								</td>
								<td>
									{{user.name}}
								</td>
								<td>
									{{formatedDate regDttm "YYYY-MM-DD"}}
								</td>
								<td>
									{{count}}
								</td>
								<td>
									{{#if attatchments}}
										<i class="material-icons file-icon">&#xE873;</i>
									{{else}}
										-
									{{/if}}

								</td>
							</tr>
						{{/each}}
					</tbody>
				{{/compare}}
			</table>			
		
	</div>
	<div class="pagination-wrapper">
		<ul class="pagination">
			{{#compare page.beginPage 1 operator=">"}}
				<li>
					<a href="{{url}}?page=" data-page="1" class="page-link {{page.className}}">&laquo; <spring:message code="page.first"/></a>
				</li>
				<li>
					<a href="{{url}}?page={{beforePage page.beginPage}}" data-page={{beforePage page.beginPage}} class="page-link {{className}}">...</a>
				</li>	
			{{/compare}}
		
			{{#for page.beginPage page.endPage 1}}
				{{#compare this ../page.currentPage operator="=="}}
					<li class="active">
						<a href="{{../../url}}?page={{this}}" data-page="{{this}}" class="page-link {{../../page.className}}">{{this}}</a>
					</li>
				{{else}}
					<li>
						<a href="{{../../url}}?page={{this}}" class="page-link {{../../page.className}}">{{this}}</a>
					</li>
				{{/compare}}
			{{/for}}
		
			{{#compare page.endPage page.totalPages operator="<"}}
				<li>
					<a href="{{url}}?page={{nextPage page.endPage}}" data-page="{{nextPage page.endPage}}" class="page-link {{page.className}}">...</a>
				</li>
				<li>
					<a href="{{url}}?page={{nextPage page.totalPages}}" data-page={{page.totalPages}} class="page-link {{page.className}}"><spring:message code="page.last"/> &raquo;</a>
				</li>
			{{/compare}}
		</ul>
	</div>
</script>

<script id="board-gallary-template" type="text/x-handlebars-template">
	<div class="list-board-wrapper">
		<div class="row gallery-boards">
			{{#each boards}}
				<div class="col-sm-6 col-md-4">
					<div class="board-gallery-item">
                        {{#if ../boardType.urlType }}
                            <a target="_blank" href="{{linkUrl}}">
                                <div class="board-img">
                                    <img src="{{picture}}"
                                        class="img-responsive"/>
                                </div>
                                <div class="board-title">
                                    {{title}}
                                    {{#compare ../../boardType.name "digitalEducation" operator="=="}}
                                        <br>
                                        {{formatedDate ../regDttm "YYYY.MM.DD"}}
                                    {{/compare}}
                                    {{#compare ../../boardType.name "sciencePlay" operator="=="}}
                                        <br>
                                        {{formatedDate ../regDttm "YYYY.MM.DD"}}
                                    {{/compare}}
                                </div>
                            </a>
                        {{else}}
                            <a href="{{../../url}}/{{id}}" >
                                <div class="board-img">
                                    <img src="{{picture}}"
                                        class="img-responsive"/>
                                </div>
                                <div class="board-title">
                                    {{title}}
                                    {{#compare ../../boardType.name "digitalEducation" operator="=="}}
                                        <br>
                                        {{formatedDate ../regDttm "YYYY.MM.DD"}}
                                    {{/compare}}
                                    {{#compare ../../boardType.name "sciencePlay" operator="=="}}
                                        <br>
                                        {{formatedDate ../regDttm "YYYY.MM.DD"}}
                                    {{/compare}}
                                </div>
                            </a>
                        {{/if}}
						
					</div>
				</div>
			{{/each}}
		</div>
	</div>
	<div class="pagination-wrapper">
		<ul class="pagination">
			{{#compare page.beginPage 1 operator=">"}}
				<li>
					<a href="{{url}}?page=" data-page="1" class="page-link {{page.className}}">&laquo; <spring:message code="page.first"/></a>
				</li>
				<li>
					<a href="{{url}}?page={{beforePage page.beginPage}}" data-page={{beforePage page.beginPage}} class="page-link {{className}}">...</a>
				</li>	
			{{/compare}}
		
			{{#for page.beginPage page.endPage 1}}
				{{#compare this ../page.currentPage operator="=="}}
					<li class="active">
						<a href="{{../../url}}?page={{this}}" data-page="{{this}}" class="page-link {{../../page.className}}">{{this}}</a>
					</li>
				{{else}}
					<li>
						<a href="{{../../url}}?page={{this}}" class="page-link {{../../page.className}}">{{this}}</a>
					</li>
				{{/compare}}
			{{/for}}
		
			{{#compare page.endPage page.totalPages operator="<"}}
				<li>
					<a href="{{url}}?page={{nextPage page.endPage}}" data-page="{{nextPage page.endPage}}" class="page-link {{page.className}}">...</a>
				</li>
				<li>
					<a href="{{url}}?page={{nextPage page.totalPages}}" data-page={{page.totalPages}} class="page-link {{page.className}}"><spring:message code="page.last"/> &raquo;</a>
				</li>
			{{/compare}}
		</ul>
	</div>
</script>
